--function CreateStateMachine(_Type,_PlatformId,_NpcId,_X,_Y)
--
--BeginDefinition(_Type, _PlatformId, _NpcId, _X, _Y)
--
--OnOneTimeEvent
--{
--	Actions = {
--		SetEffect{Effect = "CastAirSilent", NpcId = _NpcId},
--	},
--}
--
--EndDefinition()
--
--end
