--function CreateStateMachine(_Type,_PlatformId,_NpcId,_X,_Y)
--
--BeginDefinition(_Type,_PlatformId,_NpcId,_X,_Y)
--
--OneTimeInitAction( LookAtFigure{Target = Avatar} )
--OneTimeInitAction( HoldPosition{} )
--
--EndDefinition()
--
--end
