
EnvSoundMgr:SetUpdateTimer(0.1)
EnvSoundMgr:SetMasterVolume(2.0)

EnvSoundCol:Reset()

EnvSoundCol:AttachTexture("landscape_island_transparency"	,"unknown")
-- EnvSoundCol:AttachTexture("landscape_island_001_base"		,"stone")


EnvSoundCol:AttachTexture("landscape_island_001_baseD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_002_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_003_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_004_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_005_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_006_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_007_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_008_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_009_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_010_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_011_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_012_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_013_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_014_stoneD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_015_stoneD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_016_desertD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_017_desertD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_018_pathD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_019_snowD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_020_snowD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_021_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_022_loamD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_023_loamD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_024_lakeD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_025_flowersD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_026_hayD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_027_mudD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_028_mudD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_029_mudD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_030_mudD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_031_desertD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_032_rockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_033_grassrockD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_034_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_035_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_036_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_037_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_038_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_039_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_040_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_041_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_042_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_043_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_044_lavapathD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_045_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_046_lavapathD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_047_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_048_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_049_lavarockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_050_lavapathD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_051_lavasandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_052_lavarockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_053_pathD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_054_mudD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_055_pathD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_056_mudD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_057_desertD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_058_sandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_059_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_060_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_061_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_062_grassrockD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_063_grassrockD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_064_grassD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_065_grassD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_066_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_067_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_068_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_069_grassD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_070_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_071_grassD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_072_grassD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_073_grassD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_074_drymudD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_075_stonemudD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_076_stonemudD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_077_stonegrassD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_078_stonemudD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_079_stonemudD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_080_stonegrassD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_081_bluestoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_082_stonegrassD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_083_grassD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_084_stoneD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_085_grassD"	,"swamp")
EnvSoundCol:AttachTexture("landscape_island_086_stoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_087_stoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_088_pathD"	,"unknown")
EnvSoundCol:AttachTexture("landscape_island_089_redstoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_090_redstoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_091_redstoneD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_092_pathD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_093_pathD"	,"grass")
EnvSoundCol:AttachTexture("landscape_island_094_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_095_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_096_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_097_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_098_glacierD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_099_mudD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_100_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_101_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_102_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_103_sandD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_104_sandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_105_sandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_106_sandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_107_sandD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_108_sandD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_109_sandblendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_110_sandblendD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_111_blendD"	,"stone")
EnvSoundCol:AttachTexture("landscape_island_112_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_113_blendD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_114_blendD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_115_blendD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_116_blendD"	,"snow")
EnvSoundCol:AttachTexture("landscape_island_117_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_118_blendD"	,"desert")
EnvSoundCol:AttachTexture("landscape_island_119_blendD"	,"desert")




--	syntax: AttachSound(<name of wave>,<volume>,<propability>,<codec>,<name of category>);
-- 	volumes
--		(0 min - 1 max) * random(seed codec) * visibility
--	propability
--		0-1



-- Codec Syntax ist binär

-- Random Volume = 1
-- Random Pan = 2
-- Random Volume & Random Pan = 3
-- Nur Nachtaktiv = 4
-- Nachtaktiv + Random Volume = 5
-- Nachtaktiv + Random Pan = 6
-- Nachtaktiv + Pan + Volume = 7

-- lange ENV Sounds

EnvSoundCol:AttachSound("atmo_snow_loop_wind"		,0.8,0.3,0		,"snow"	)
EnvSoundCol:AttachSound("atmo_grass_loop_wind"		,0.5,0.3,0		,"grass"	)
EnvSoundCol:AttachSound("atmo_desert_loop_wind"		,0.5,0.3,0		,"desert"	)
-- EnvSoundCol:AttachSound("atmo_grass_loop_day"		,0.8,1,0		,"grass"	)
-- EnvSoundCol:AttachSound("atmo_swamp_loop_day"		,0.8,1,0		,"swamp"	)
EnvSoundCol:AttachSound("atmo_grass_loop_night"		,0.7,0.8,4		,"grass"	)
EnvSoundCol:AttachSound("atmo_desert_loop_night"		,0.8,0.3,4		,"desert"	)
EnvSoundCol:AttachSound("atmo_swamp_loop_night"		,0.7,0.8,4		,"swamp"	)

-- Kurze ENV Sounds

-- Snow Birds

EnvSoundCol:AttachSound("atmo_snow_one_bird_01"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_02"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_03"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_04"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_05"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_06"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_07"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_08"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_09"			,1,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_03"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_04"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_05"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_06"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_07"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_08"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_09"			,1,0.4,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_10"			,1,0.4,3		,"snow"		)
-- Snow Birds Add On 1
if SndAddonInstalled then
	EnvSoundCol:AttachSound("atmo_snow_one_bird_30"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_31"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_32"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_33"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_34"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_35"			,1,0.3,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_36"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_30"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_31"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_32"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_33"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_34"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_35"			,1,0.3,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_bird_36"			,1,0.3,7		,"snow"		)
end

-- Grass Birds

EnvSoundCol:AttachSound("atmo_grass_one_bird_01"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_02"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_03"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_04"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_05"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_06"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_07"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_08"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_09"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_10"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_11"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_12"			,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_13"			,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_14"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bird_15"			,1,0.3,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_03"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_04"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_05"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_07"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_08"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_09"				,1,0.2,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_10"				,1,0.2,7		,"grass"		)

-- Swamp Birds

EnvSoundCol:AttachSound("atmo_swamp_one_bird_01"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_02"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_03"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_04"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_05"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_06"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_07"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_08"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_09"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_10"			,1,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_01"			,1,0.2,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_bird_02"			,1,0.2,7		,"swamp"		)
-- Swamp Birds Add On1
if SndAddonInstalled then
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_30"			,1,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_31"			,1,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_32"			,1,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_33"			,1,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_34"			,1,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_30"			,1,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_31"			,1,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_32"			,1,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_33"			,1,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_bird_34"			,1,0.2,7		,"swamp"		)
end

-- Desert Birds

EnvSoundCol:AttachSound("atmo_desert_one_bird_01"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_02"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_03"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_04"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_05"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_06"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_07"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_08"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_09"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_10"			,1,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_07"			,1,0.2,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_08"			,1,0.4,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_09"			,1,0.5,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_bird_10"			,1,0.4,7		,"desert"		)

-- Stone Birds

EnvSoundCol:AttachSound("atmo_stone_one_bird_01"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_02"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_03"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_04"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_05"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_06"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_07"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_08"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_09"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_10"			,1,0.2,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_08"			,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_bird_10"			,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_03"				,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_04"				,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_07"				,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_08"				,1,0.2,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_snow_one_bird_10"				,1,0.2,7		,"stone"		)

-- Winds

EnvSoundCol:AttachSound("atmo_grass_one_wind_01"			,0.8,0.5,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_01"			,0.8,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_02"			,0.8,0.5,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_02"			,0.8,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_03"			,0.8,0.5,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_03"			,0.8,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_04"			,0.8,0.5,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_wind_04"			,0.8,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_snow_one_wind_01"				,0.8,0.5,3		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_01"				,0.8,0.5,7		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_02"				,0.8,0.5,3		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_02"				,0.8,0.5,7		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_03"				,0.8,0.5,3		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_03"				,0.8,0.5,7		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_04"				,0.8,0.5,3		,"snow"			)
EnvSoundCol:AttachSound("atmo_snow_one_wind_04"				,0.8,0.5,7		,"snow"			)
EnvSoundCol:AttachSound("atmo_stone_one_wind_01"			,0.8,0.5,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_01"			,0.8,0.5,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_02"			,0.8,0.5,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_02"			,0.8,0.5,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_03"			,0.8,0.5,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_03"			,0.8,0.5,7		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_04"			,0.8,0.5,3		,"stone"		)
EnvSoundCol:AttachSound("atmo_stone_one_wind_04"			,0.8,0.5,7		,"stone"		)
-- Winds Add On 1
if SndAddonInstalled then
	EnvSoundCol:AttachSound("atmo_snow_one_wind_30"			,0.8,0.4,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_31"			,0.8,0.4,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_32"			,0.8,0.4,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_33"			,0.8,0.4,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_34"			,0.8,0.4,3		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_30"			,0.8,0.4,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_31"			,0.8,0.4,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_32"			,0.8,0.4,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_33"			,0.8,0.4,7		,"snow"		)
	EnvSoundCol:AttachSound("atmo_snow_one_wind_34"			,0.8,0.4,7		,"snow"		)
end

-- Animals

EnvSoundCol:AttachSound("atmo_snow_one_wolf_01"				,0.8,0.3,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_02"				,0.8,0.3,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_03"				,0.8,0.3,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_04"				,0.8,0.3,7		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_01"				,0.8,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_02"				,0.8,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_03"				,0.8,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_04"				,0.8,0.3,3		,"snow"		)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_01"				,0.8,0.3,7		,"grass"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_02"				,0.8,0.3,7		,"grass"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_03"				,0.8,0.3,7		,"grass"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_04"				,0.8,0.3,7		,"grass"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_01"				,0.8,0.3,7		,"stone"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_02"				,0.8,0.3,7		,"stone"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_03"				,0.8,0.3,7		,"stone"	)
EnvSoundCol:AttachSound("atmo_snow_one_wolf_04"				,0.8,0.3,7		,"stone"	)
-- Wolves Add On1
if SndAddonInstalled then
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_30"				,0.8,0.3,7		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_31"				,0.8,0.3,7		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_32"				,0.8,0.3,7		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_33"				,0.8,0.3,7		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_34"				,0.8,0.3,7		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_30"				,0.8,0.3,3		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_31"				,0.8,0.3,3		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_32"				,0.8,0.3,3		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_33"				,0.8,0.3,3		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_34"				,0.8,0.3,3		,"snow"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_30"				,0.8,0.3,7		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_31"				,0.8,0.3,7		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_32"				,0.8,0.3,7		,"grass"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_33"				,0.8,0.3,7		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_34"				,0.8,0.3,7		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_30"				,0.8,0.3,3		,"grass"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_31"				,0.8,0.3,3		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_32"				,0.8,0.3,3		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_33"				,0.8,0.3,3		,"stone"	)
	EnvSoundCol:AttachSound("atmo_snow_one_wolf_34"				,0.8,0.3,3		,"grass"	)
end

EnvSoundCol:AttachSound("atmo_grass_one_cricket_01"			,0.7,0.4,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_02"			,0.7,0.4,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_03"			,0.7,0.4,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_04"			,0.7,0.4,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_01"			,0.6,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_02"			,0.6,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_03"			,0.6,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_cricket_04"			,0.6,0.5,7		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bee_01"				,0.7,0.5,3		,"grass"		)
EnvSoundCol:AttachSound("atmo_grass_one_bee_02"				,0.7,0.5,3		,"grass"		)

EnvSoundCol:AttachSound("atmo_swamp_one_frog_01"			,0.8,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_02"			,0.8,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_03"			,0.8,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_04"			,0.8,0.3,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_01"			,0.5,0.4,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_02"			,0.7,0.4,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_03"			,0.7,0.4,3		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_04"			,0.8,0.4,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_05"			,0.8,0.4,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_frog_06"			,0.8,0.4,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_04"			,0.6,0.5,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_05"			,0.6,0.5,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_02"			,0.4,0.5,7		,"swamp"		)
EnvSoundCol:AttachSound("atmo_swamp_one_cricket_03"			,0.6,0.5,7		,"swamp"		)
-- Add On1 Frogs 
if SndAddonInstalled then
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_30"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_31"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_32"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_33"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_34"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_35"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_36"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_37"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_38"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_39"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_40"			,0.8,0.2,7		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_30"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_31"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_32"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_33"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_34"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_35"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_36"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_37"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_38"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_39"			,0.8,0.2,3		,"swamp"		)
	EnvSoundCol:AttachSound("atmo_swamp_one_frog_40"			,0.8,0.2,3		,"swamp"		)
end

EnvSoundCol:AttachSound("atmo_desert_one_snake_01"			,0.8,0.4,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_snake_02"			,0.8,0.4,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_snake_03"			,0.8,0.4,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_01"			,0.7,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_02"			,0.7,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_03"			,0.7,0.3,3		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_01"			,0.6,0.6,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_02"			,0.4,0.6,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_cricket_03"			,0.4,0.6,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_coyote_01"			,0.8,0.4,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_coyote_02"			,0.8,0.4,7		,"desert"		)
EnvSoundCol:AttachSound("atmo_desert_one_coyote_03"			,0.8,0.4,7		,"desert"		)


--EnvSoundCol:Report()