-------------------------------------------------------------------------------
-- Desc: SQL-export
--
-- File is autocreated DO NOT EDIT!
-------------------------------------------------------------------------------

return {
[1] = {mesh={"building_human_main2", "building_human_main2_trough", "building_human_main2_decal", "building_human_main2_frame", }, selectionscaling=14},
[2] = {mesh={"building_human_main1", "building_human_main1_lamp1", "building_human_main1_lamp2", "building_human_main1_well", "building_human_main1_decal", "building_human_main1_frame", }, selectionscaling=8},
[3] = {mesh={"building_human_main3", "building_human_main3_coach", "building_human_main3_flag1", "building_human_main3_flag2", "building_human_main3_decal", "building_human_main3_frame", }, selectionscaling=18},
[4] = {mesh={"building_human_woodcutterhut", "building_human_woodcutterhut_hatchet", "building_human_woodcutterhut_sawlog", "building_human_woodcutterhut_trunks", "building_human_woodcutterhut_decal", "building_human_woodcutterhut_frame", }, selectionscaling=8},
[5] = {mesh={"building_human_sawmill", "building_human_sawmill_trunks", "building_human_sawmill_decal", "building_human_sawmill_frame", "building_human_sawmill_saw", }, selectionscaling=8},
[6] = {mesh={"building_human_cattlebreeding", "building_human_cattlebreeding_decal", "building_human_cattlebreeding_frame", "building_human_cattlebreeding_dungheap", }, selectionscaling=13},
[7] = {mesh={"building_human_quarry", "building_human_quarry_pickaxes", "building_human_quarry_rock1", "building_human_quarry_rock2", "building_human_quarry_rock3", "building_human_quarry_wheelbarrow", "building_human_quarry_decal", "building_human_quarry_frame", }, selectionscaling=9},
[8] = {mesh={"building_human_foodstore", "building_human_foodstore_crane", "building_human_foodstore_decal", "building_human_foodstore_frame", }, selectionscaling=15},
[9] = {mesh={"building_human_huntinglodge", "building_human_huntinglodge_trap", "building_human_huntinglodge_decal", "building_human_huntinglodge_frame", }, selectionscaling=8},
[10] = {mesh={"building_human_fisherhut", "building_human_fisherhut_decal", "building_human_fisherhut_frame", }, selectionscaling=8},
[11] = {mesh={"building_human_fisherhut_advanced", "building_human_fisherhut_advanced_basket", "building_human_fisherhut_advanced_flag", "building_human_fisherhut_advanced_decal", "building_human_fisherhut_advanced_net", "building_human_fisherhut_frame", }, selectionscaling=18},
[12] = {mesh={"building_human_grainfarm", "building_human_grainfarm_decal", "building_human_grainfarm_frame", }, selectionscaling=14},
[13] = {mesh={"building_human_tower_crossbow", "building_human_tower_crossbow_decal", "building_human_tower_crossbow_frame", }, selectionscaling=4.5},
[14] = {mesh={"building_human_mine", "building_human_mine_decal", "building_human_mine_tower", "building_human_mine_frame", }, selectionscaling=13.8},
[15] = {mesh={"building_human_smeltingworks", "building_human_smeltingworks_ramp", "building_human_smeltingworks_decal", "building_human_smeltingworks_frame", }, selectionscaling=15},
[16] = {mesh={"building_human_shrine_of_light", "building_human_shrine_of_light_decal", "building_human_shrine_of_light_frame", }, selectionscaling=6},
[17] = {mesh={"building_human_temple_of_light", "building_human_temple_of_light_decal", "building_human_temple_of_light_frame", }, selectionscaling=12},
[18] = {mesh={"building_human_academy", "building_human_academy_decal", "building_human_academy_frame", }, selectionscaling=6},
[19] = {mesh={"building_human_forge_steel", "building_human_forge_steel_decal", "building_human_forge_steel_frame", }, selectionscaling=12},
[20] = {mesh={"building_elf_headquarter_small", "building_elf_headquarter_small_decal", "building_elf_headquarter_small_frame", }, selectionscaling=10},
[21] = {mesh={"building_elf_headquarter_medium", "building_elf_headquarter_medium_decal", "building_elf_headquarter_medium_frame", }, selectionscaling=14.3},
[22] = {mesh={"building_elf_headquarter_large", "building_elf_headquarter_large_decal", "building_elf_headquarter_large_frame", }, selectionscaling=18.4},
[23] = {mesh={"building_elf_forester", "building_elf_forrester_decal", "building_elf_forester_frame", }, selectionscaling=9},
[24] = {mesh={"building_elf_woodcutterhut_advanced", "building_elf_woodcutterhut_advanced_decal", "building_elf_woodcutterhut_advanced_frame", }, selectionscaling=18},
[25] = {mesh={"building_elf_hallofancient", "building_elf_hallofancient_decal", "building_elf_hallofancient_frame", }, selectionscaling=10},
[26] = {mesh={"building_elf_foodstore", "building_elf_foodstore_decal", "building_elf_foodstore_frame", }, selectionscaling=13.3},
[27] = {mesh={"building_elf_lenyagather", "building_elf_lenyagather_decal", "building_elf_lenyagather_frame", }, selectionscaling=5},
[28] = {mesh={"building_elf_woodcutterhut", "building_elf_woodcutterhut_decal", "building_elf_woodcutterhut_frame", }, selectionscaling=12},
[29] = {mesh={"building_elf_huntinglodge", "building_elf_huntinglodge_decal", "building_elf_huntinglodge_frame", }, selectionscaling=10},
[30] = {mesh={"building_elf_armory_iron", "building_elf_armory_iron_decal", "building_elf_armory_iron_frame", }, selectionscaling=14},
[31] = {mesh={"building_elf_huntinglodge_advanced", "building_elf_huntinglodge_advanced_decal", "building_elf_huntinglodge_advanced_frame", }, selectionscaling=11},
[32] = {mesh={"building_human_tower_whitemagic", "building_human_tower_whitemagic_decal", "building_human_tower_whitemagic_frame", }, selectionscaling=7},
[33] = {mesh={"building_elf_collector", "building_elf_collector_decal", "building_elf_collector_frame", }, selectionscaling=11},
[34] = {mesh={"building_elf_armory", "building_elf_armory_decal", "building_elf_armory_frame", }, selectionscaling=12.5},
[36] = {mesh={"building_elf_ailantary", "building_elf_ailantary_decal", "building_elf_ailantary_frame", }, selectionscaling=11},
[37] = {mesh={"building_elf_tower_bow", }, selectionscaling=1},
[38] = {mesh={"building_elf_tower_bow", "building_elf_tower_bow_decal", "building_elf_tower_bow_frame", }, selectionscaling=5},
[39] = {mesh={"building_elf_tower_icemagic", "building_elf_tower_icemagic_decal", "building_elf_tower_icemagic_frame", }, selectionscaling=5},
[40] = {mesh={"building_elf_special_archery", "building_elf_special_archery_decal", "building_elf_special_archery_frame", }, selectionscaling=10},
[41] = {mesh={"building_dwarf_headquarter_small", "building_dwarf_headquarter_small_decal", "building_dwarf_headquarter_small_frame", }, selectionscaling=9},
[42] = {mesh={"building_dwarf_headquarter_medium", "building_dwarf_headquarter_medium_decal", "building_dwarf_headquarter_medium_frame", }, selectionscaling=12},
[43] = {mesh={"building_dwarf_headquarter_large", "building_dwarf_headquarter_large_decal", "building_dwarf_headquarter_large_frame", }, selectionscaling=14},
[44] = {mesh={"building_dwarf_quarry", "building_dwarf_quarry_decal", "building_dwarf_quarry_frame", }, selectionscaling=10},
[45] = {mesh={"building_dwarf_great_armory", "building_dwarf_great_armory_decal", "building_dwarf_great_armory_frame", }, selectionscaling=9},
[46] = {mesh={"building_dwarf_stonemasonhut", "building_dwarf_stonemasonhut_decal", "building_dwarf_stonemasonhut_frame", }, selectionscaling=12},
[47] = {mesh={"building_dwarf_foodstore", "building_dwarf_foodstore_decal", "building_dwarf_foodstore_frame", }, selectionscaling=11},
[48] = {mesh={"building_dwarf_swinefarm", "building_dwarf_swinefarm_decal", "building_dwarf_swinefarm_frame", }, selectionscaling=12},
[49] = {mesh={"building_dwarf_mine", "building_dwarf_mine_decal", "building_dwarf_mine_frame", }, selectionscaling=11},
[51] = {mesh={"building_dwarf_mine_mithril", "building_dwarf_mine_mithril_decal", "building_dwarf_mine_mithrill_frame", }, selectionscaling=12},
[52] = {mesh={"building_dwarf_smeltingworks", "building_dwarf_smeltingworks_decal", "building_dwarf_smeltingworks_frame", }, selectionscaling=12},
[53] = {mesh={"building_dwarf_forge", "building_dwarf_forge_decal", "building_dwarf_forge_frame", }, selectionscaling=8},
[55] = {mesh={"building_elf_sawmill", "building_elf_sawmill_decal", "building_elf_sawmill_frame", "building_elf_sawmill_saw", }, selectionscaling=10},
[56] = {mesh={"building_darkelf_forge_master", "building_darkelf_forge_master_decal", "building_darkelf_forge_master_frame", }, selectionscaling=10},
[57] = {mesh={"building_orc_hallofglory", "building_orc_hallofglory_frame", "building_orc_hallofglory_decal", }, selectionscaling=13},
[58] = {mesh={"building_orc_headquarter_small", "building_orc_headquarter_small_decal", "building_orc_headquarter_small_frame", }, selectionscaling=10.8},
[59] = {mesh={"building_orc_headquarter_medium", "building_orc_headquarter_medium_decal", "building_orc_headquarter_medium_frame", }, selectionscaling=16},
[60] = {mesh={"building_orc_headquarter_large", "building_orc_headquarter_large_frame", "building_orc_headquarter_large_decal", }, selectionscaling=13},
[61] = {mesh={"building_orc_woodcutterhut", "building_orc_woodcutterhut_decal", "building_orc_woodcutterhut_frame", }, selectionscaling=7},
[62] = {mesh={"building_orc_smeltingworks", "building_orc_smeltingworks_decal", "building_orc_smeltingworks_frame", }, selectionscaling=10.5},
[63] = {mesh={"building_orc_foodstore", "building_orc_foodstore_box", "building_orc_foodstore_decal", "building_orc_foodstore_frame", }, selectionscaling=10},
[64] = {mesh={"building_orc_huntinglodge", "building_orc_huntinglodge_decal", "building_orc_huntinglodge_frame", }, selectionscaling=9.3},
[65] = {mesh={"building_orc_fisherhut", "building_orc_fisherhut_decal", "building_orc_fisherhut_frame", }, selectionscaling=9.8},
[66] = {mesh={"building_orc_boarbreeding", "building_orc_boarbreeding_decal", "building_orc_boarbreeding_frame", }, selectionscaling=9.8},
[67] = {mesh={"building_orc_mine", "building_orc_mine_decal", "building_orc_mine_frame", }, selectionscaling=17},
[68] = {mesh={"building_orc_forge", "building_orc_forge_decal", "building_orc_forge_frame", }, selectionscaling=7},
[69] = {mesh={"building_orc_croptent", "building_orc_croptent_decal", "building_orc_croptent_frame", }, selectionscaling=7},
[70] = {mesh={"building_orc_shamanhut", "building_orc_shamanhut_decal", "building_orc_shamanhut_frame", }, selectionscaling=11},
[71] = {mesh={"building_orc_tower_firemagic", "building_orc_tower_firemagic_decal", "building_orc_tower_firemagic_frame", }, selectionscaling=6},
[72] = {mesh={"building_orc_bloodshrine", "building_orc_bloodshrine_decal", "building_orc_bloodshrine_frame", }, selectionscaling=8},
[73] = {mesh={"building_troll_haedquarter_small", "building_troll_haedquarter_small_decal", "building_troll_headquarter_small_frame", }, selectionscaling=11},
[74] = {mesh={"building_troll_headquarter_medium", "building_troll_headquarter_medium_decal", "building_troll_headquarter_medium_frame", }, selectionscaling=16},
[75] = {mesh={"building_human_forge", "building_human_forge_decal", "building_human_forge_frame", }, selectionscaling=10},
[76] = {mesh={"building_troll_headquarter_large", "building_troll_headquarter_large_decal", "building_troll_headquarter_large_frame", }, selectionscaling=17},
[77] = {mesh={"building_troll_woodcutterhut", "building_troll_woodcutterhut_decal", "building_troll_woodcutterhut_frame", }, selectionscaling=18},
[78] = {mesh={"building_troll_quarry", "building_troll_quarry_decal", "building_troll_quarry_frame", }, selectionscaling=11},
[79] = {mesh={"building_troll_foodstore", "building_troll_foodstore_decal", "building_troll_foodstore_frame", }, selectionscaling=16},
[80] = {mesh={"building_troll_huntinglodge", "building_troll_huntinglodge_decal", "building_troll_huntinglodge_frame", }, selectionscaling=11},
[81] = {mesh={"building_troll_stone_cutter", "building_troll_stone_cutter_decal", "building_troll_stone_cutter_frame", }, selectionscaling=11},
[82] = {mesh={"building_troll_corpsecollector", "building_troll_corpsecollector_decal", "building_troll_corpsecollector_frame", }, selectionscaling=19},
[83] = {mesh={"building_troll_clubmaker", "building_troll_clubmaker_decal", "building_troll_clubmaker_frame", }, selectionscaling=15},
[84] = {mesh={"building_troll_tower_stone", "building_troll_tower_stone_decal", "building_troll_tower_stone_frame", }, selectionscaling=9},
[85] = {mesh={"building_darkelf_headquarter_small", "building_darkelf_headquarter_small_decal", "building_darkelf_headquarter_small_frame", }, selectionscaling=8},
[86] = {mesh={"building_darkelf_headquarter_medium", "building_darkelf_headquarter_medium_decal", "building_darkelf_headquarter_medium_frame", }, selectionscaling=11},
[87] = {mesh={"building_darkelf_headquarter_large", "building_darkelf_headquarter_large_decal", "building_darkelf_headquarter_large_frame", }, selectionscaling=16},
[88] = {mesh={"building_darkelf_quarry", "building_darkelf_quarry_decal", "building_darkelf_quarry_frame", }, selectionscaling=10},
[89] = {mesh={"building_darkelf_mine_mithril", "building_darkelf_mine_mithrill_decal", "building_darkelf_mine_mithrill_frame", }, selectionscaling=11},
[90] = {mesh={"building_darkelf_stonemasonhut", "building_darkelf_stonemasonhut_decal", "building_darkelf_stonemasonhut_frame", "building_darkelf_stonemasonhut_saw", }, selectionscaling=10},
[91] = {mesh={"building_darkelf_foodstore", "building_darkelf_foodstore_crane", "building_darkelf_foodstore_decal", "building_darkelf_foodstore_frame", }, selectionscaling=12},
[92] = {mesh={"building_darkelf_fungusfarm", "building_darkelf_fungusfarm_decal", "building_darkelf_fungusfarm_frame", }, selectionscaling=15},
[93] = {mesh={"building_darkelf_breeder", "building_darkelf_breeder_decal", "building_darkelf_breeder_frame", }, selectionscaling=13},
[94] = {mesh={"building_darkelf_smeltingworks", "building_darkelf_smeltingworks_decal", "building_darkelf_smeltingworks_frame", }, selectionscaling=15},
[95] = {mesh={"building_darkelf_mine", "building_darkelf_mine_decal", "building_darkelf_mine_frame", }, selectionscaling=13},
[96] = {mesh={"building_darkelf_forge", "building_darkelf_forge_decal", "building_darkelf_forge_frame", }, selectionscaling=10},
[98] = {mesh={"building_darkelf_arcanum", "building_darkelf_arcanum_decal", "building_darkelf_arcanum_frame", }, selectionscaling=6.5},
[99] = {mesh={"building_darkelf_onyxshrine", "building_darkelf_onyxshrine_decal", "building_darkelf_onyxshrine_frame", }, selectionscaling=7},
[100] = {mesh={"building_darkelf_onyxtower", "building_darkelf_onyxtower_decal", "building_darkelf_onyxtower_frame", }, selectionscaling=9},
[102] = {mesh={"building_darkelf_tower_blackmagic", "building_darkelf_tower_blackmagic_decal", "building_darkelf_tower_blackmagic_frame", }, selectionscaling=5},
[103] = {mesh={"building_darkelf_tower_mentalmagic", "building_darkelf_tower_mentalmagic_decal", "building_darkelf_tower_mentalmagic_frame", }, selectionscaling=5},
[104] = {mesh={"building_darkelf_darkacademy", "building_darkelf_darkacademy_decal", "building_darkelf_darkacademy_frame", }, selectionscaling=12},
[106] = {mesh={"building_orc_headquarter_small", "building_orc_headquarter_small_decal", }, selectionscaling=10.8},
[107] = {mesh={"building_orc_headquarter_medium", "building_orc_headquarter_medium_decal", }, selectionscaling=16},
[108] = {mesh={"building_orc_headquarter_large", "building_orc_headquarter_large_decal", }, selectionscaling=13},
[109] = {mesh={"building_orc_boarbreeding", "building_orc_boarbreeding_decal", }, selectionscaling=9.8},
[110] = {mesh={"building_orc_fisherhut", "building_orc_fisherhut_decal", }, selectionscaling=7.5},
[111] = {mesh={"building_orc_foodstore", "building_orc_foodstore_decal", }, selectionscaling=9},
[112] = {mesh={"building_orc_forge", "building_orc_forge_decal", }, selectionscaling=7},
[113] = {mesh={"building_orc_mine", "building_orc_mine_decal", }, selectionscaling=19},
[114] = {mesh={"building_orc_woodcutterhut", "building_orc_woodcutterhut_decal", }, selectionscaling=7},
[115] = {mesh={"worlditem_hut_small", "worlditem_hut_small_decal", }, selectionscaling=10.8},
[116] = {mesh={"worlditem_hut_large", "worlditem_hut_large_decal", }, selectionscaling=11},
[117] = {mesh={"building_troll_headquarter_large", "building_troll_headquarter_large_decal", }, selectionscaling=17},
[118] = {mesh={"building_troll_headquarter_medium", "building_troll_headquarter_medium_decal", }, selectionscaling=16},
[119] = {mesh={"building_troll_haedquarter_small", "building_troll_haedquarter_small_decal", }, selectionscaling=11},
[120] = {mesh={"building_troll_tower_stone", "building_troll_tower_stone_decal", }, selectionscaling=8},
[121] = {mesh={"building_troll_foodstore", "building_troll_foodstore_decal", }, selectionscaling=16},
[122] = {mesh={"building_troll_quarry", "building_troll_quarry_decal", }, selectionscaling=11},
[123] = {mesh={"building_human_tower_crossbow", "building_human_tower_crossbow_decal", }, selectionscaling=8},
[124] = {mesh={"building_human_tower_crossbow", }, selectionscaling=8},
[125] = {mesh={"building_troll_clubmaker", "building_troll_clubmaker_decal", }, selectionscaling=15},
[126] = {mesh={"building_troll_huntinglodge", "building_troll_huntinglodge_decal", }, selectionscaling=11},
[127] = {mesh={"building_troll_corpsecollector", "building_troll_corpsecollector_decal", }, selectionscaling=15},
[128] = {mesh={"building_human_forge", "building_human_forge_decal", "building_human_forge_frame", }, selectionscaling=10},
[129] = {mesh={"building_human_main3", "building_human_main3_coach", "building_human_main3_flag1", "building_human_main3_flag2", "building_human_main3_lamp1", "building_human_main3_lamp2", "building_human_main3_decal", }, selectionscaling=18},
[130] = {mesh={"building_human_main2", "building_human_main2_trough", "building_human_main2_decal", "building_human_main2_frame", }, selectionscaling=14},
[131] = {mesh={"building_human_forge_steel", "building_human_forge_steel_decal", "building_human_forge_steel_frame", }, selectionscaling=11.6},
[132] = {mesh={"building_human_foodstore", "building_human_foodstore_decal", "building_human_foodstore_frame", }, selectionscaling=15},
[133] = {mesh={"building_darkelf_shadowforge", "building_darkelf_shadowforge_decal", "building_darkelf_shadowforge_frame", }, selectionscaling=7.5},
[134] = {mesh={"building_dwarf_sanctuary", "building_dwarf_sanctuary_decal", "building_dwarf_sanctuary_frame", }, selectionscaling=11},
[135] = {mesh={"building_dwarf_truesilver_forge", "building_dwarf_truesilver_forge_decal", "building_dwarf_truesilver_forge_frame", }, selectionscaling=8.5},
[136] = {mesh={"building_human_shooting_range", "building_human_shooting_range_decal", "building_human_shooting_range_frame", }, selectionscaling=13},
[137] = {mesh={"building_orc_macecarver", "building_orc_macecarver_decal", "building_orc_macecarver_frame", }, selectionscaling=14},
[138] = {mesh={"building_orc_darkforge", "building_orc_darkforge_decal", "building_orc_darkforge_frame", }, selectionscaling=11},
[139] = {mesh={"building_troll_ironhouse", "building_troll_ironhouse_decal", "building_troll_ironhouse_frame", }, selectionscaling=9},
[140] = {mesh={"building_troll_blacksmith", "building_troll_blacksmith_decal", "building_troll_blacksmith_frame", }, selectionscaling=8},
[141] = {mesh={"building_darkelf_headquarter_small", }, selectionscaling=8},
[142] = {mesh={"building_darkelf_forge", }, selectionscaling=12},
[143] = {mesh={"building_darkelf_onyxshrine", "building_darkelf_onyxshrine_decal", }, selectionscaling=7},
[144] = {mesh={"building_darkelf_foodstore", }, selectionscaling=12},
[145] = {mesh={"building_darkelf_headquarter_large", }, selectionscaling=16},
[146] = {mesh={"building_human_tower_crossbow", }, selectionscaling=1},
[147] = {mesh={"building_orc_tower_firemagic", "building_orc_tower_firemagic_decal", }, selectionscaling=6},
[148] = {mesh={"worlditem_spawn_undead_crypt", "worlditem_spawn_undead_crypt_decal", }, selectionscaling=7.5},
[149] = {mesh={"building_skeleton_tower_skull", "building_skeleton_tower_skull_decal", }, selectionscaling=5},
[150] = {mesh={"worlditem_portal_demon", "worlditem_portal_demon_decal", }, selectionscaling=6},
[151] = {mesh={"building_human_tower_whitemagic", "building_human_tower_whitemagic_decal", "building_human_tower_whitemagic_frame", }, selectionscaling=7},
[152] = {mesh={"worlditem_spawn_dragon", "worlditem_spawn_dragon_decal", }, selectionscaling=5.8},
[153] = {mesh={"worlditem_spawn_undead_grave", "worlditem_spawn_undead_grave_decal", }, selectionscaling=8},
[154] = {mesh={"worlditem_spawn_elemental_air", "worlditem_spawn_elemental_decal", }, selectionscaling=2},
[155] = {mesh={"worlditem_spawn_elemental_earth", "worlditem_spawn_elemental_decal", }, selectionscaling=2},
[156] = {mesh={"worlditem_spawn_elemental_fire", "worlditem_spawn_elemental_decal", }, selectionscaling=2},
[157] = {mesh={"worlditem_spawn_elemental_water", "worlditem_spawn_elemental_decal", }, selectionscaling=2},
[158] = {mesh={"worlditem_spawn_basilisk", "worlditem_spawn_basilisk_decal", }, selectionscaling=3.7},
[159] = {mesh={"worlditem_spawn_blades", "worlditem_spawn_blades_decal", }, selectionscaling=13},
[160] = {mesh={"building_blade_tower", "building_blade_tower_decal", }, selectionscaling=11},
[161] = {mesh={"nature_bush_poison", }, selectionscaling=1.4},
[162] = {mesh={"building_elf_hallofancient", "building_elf_hallofancient_decal", }, selectionscaling=10},
[163] = {mesh={"building_elf_tower_icemagic", "building_elf_tower_icemagic_decal", }, selectionscaling=5},
[164] = {mesh={"building_blade_tower", }, selectionscaling=11},
[165] = {mesh={"worlditem_soulforger_fountain", }, selectionscaling=2},
[166] = {mesh={"worlditem_soulforger_fountain", }, selectionscaling=2},
[167] = {mesh={"building_darkelf_tower_mentalmagic", "building_darkelf_tower_mentalmagic_decal", "building_darkelf_tower_mentalmagic_frame", }, selectionscaling=5},
[168] = {mesh={"building_dwarf_statue", }, selectionscaling=3},
[169] = {mesh={"building_darkelf_tower_blackmagic", "building_darkelf_tower_blackmagic_decal", }, selectionscaling=8},
[170] = {mesh={"building_darkelf_tower_blackmagic", "building_darkelf_tower_blackmagic_decal", }, selectionscaling=8},
[171] = {mesh={"building_darkelf_wall_towngate_solo", }, selectionscaling=10},
[172] = {mesh={"worlditem_poisonplant", "worlditem_poisonplant_decal", }, selectionscaling=5.8},
[173] = {mesh={"building_darkelf_headquarter_medium", "building_darkelf_headquarter_medium_decal", }, selectionscaling=11},
[174] = {mesh={"nature_prop_spider_hideout_small_3_main", "nature_prop_spider_hideout_decal", }, selectionscaling=5},
[175] = {mesh={"nature_prop_spider_hideout_medium_2_main", "nature_prop_spider_hideout_decal", }, selectionscaling=10},
[176] = {mesh={"nature_prop_spider_hideout_1_main", "nature_prop_spider_hideout_decal", }, selectionscaling=12},
[177] = {mesh={"building_darkelf_arcanum", "building_darkelf_arcanum_decal", "building_darkelf_arcanum_frame", }, selectionscaling=6.5},
[178] = {mesh={"building_darkelf_tower_blackmagic", "building_darkelf_tower_blackmagic_decal", "building_darkelf_tower_blackmagic_frame", }, selectionscaling=5},
[179] = {mesh={"building_darkelf_mine", "building_darkelf_mine_decal", "building_darkelf_mine_frame", }, selectionscaling=13},
[180] = {mesh={"building_darkelf_mine_mithril", "building_darkelf_mine_mithrill_decal", "building_darkelf_mine_mithrill_frame", }, selectionscaling=11},
[181] = {mesh={"building_darkelf_forge_master", "building_darkelf_forge_master_decal", "building_darkelf_forge_master_frame", }, selectionscaling=10},
[182] = {mesh={"building_darkelf_onyxtower", "building_darkelf_onyxtower_decal", "building_darkelf_onyxtower_frame", }, selectionscaling=9},
[183] = {mesh={"building_darkelf_fungusfarm", "building_darkelf_fungusfarm_decal", "building_darkelf_fungusfarm_frame", }, selectionscaling=15},
[184] = {mesh={"building_darkelf_shadowforge", "building_darkelf_shadowforge_decal", "building_darkelf_shadowforge_frame", }, selectionscaling=7.5},
[185] = {mesh={"building_darkelf_smeltingworks", "building_darkelf_smeltingworks_decal", "building_darkelf_smeltingworks_frame", }, selectionscaling=15},
[186] = {mesh={"building_darkelf_darkacademy", "building_darkelf_darkacademy_decal", "building_darkelf_darkacademy_frame", }, selectionscaling=12},
[187] = {mesh={"building_darkelf_quarry", "building_darkelf_quarry_decal", "building_darkelf_quarry_frame", }, selectionscaling=10},
[188] = {mesh={"building_darkelf_stonemasonhut", "building_darkelf_stonemasonhut_decal", "building_darkelf_stonemasonhut_frame", "building_darkelf_stonemasonhut_saw", }, selectionscaling=10},
[189] = {mesh={"building_darkelf_breeder", "building_darkelf_breeder_decal", "building_darkelf_breeder_frame", }, selectionscaling=13},
[190] = {mesh={"worlditem_spawn_treewraith_01", "worlditem_spawn_treewraith_01_decal", }, selectionscaling=10},
[191] = {mesh={"worlditem_spawn_treewraith_02", "worlditem_spawn_treewraith_02_decal", }, selectionscaling=10},
[192] = {mesh={"worlditem_tent_large", }, selectionscaling=9},
[193] = {mesh={"worlditem_tent_medium", }, selectionscaling=6.8},
[194] = {mesh={"worlditem_tent_small", }, selectionscaling=4.6},
[195] = {mesh={"worlditem_tent_normal", }, selectionscaling=6.8},
[196] = {mesh={"nature_prop_tent", }, selectionscaling=5.6},
[197] = {mesh={"building_darkelf_swarm", "building_darkelf_swarm_decal", "building_darkelf_swarm_frame", }, selectionscaling=5},
[198] = {mesh={"building_dwarf_swarm", "building_dwarf_swarm_decal", "building_dwarf_swarm_frame", }, selectionscaling=11},
[199] = {mesh={"building_elf_swarm", "building_elf_swarm_decal", "building_elf_swarm_frame", }, selectionscaling=5},
[200] = {mesh={"building_human_swarm", "building_human_swarm_decal", "building_human_swarm_frame", }, selectionscaling=6},
[201] = {mesh={"building_orc_swarm", "building_orc_swarm_decal", "building_orc_swarm_frame", }, selectionscaling=13},
[202] = {mesh={"building_troll_swarm", "building_troll_swarm_decal", "building_troll_swarm_frame", }, selectionscaling=5},
[203] = {mesh={"building_human_siege", "building_human_siege_decal", "building_human_siege_frame", }, selectionscaling=8},
[204] = {mesh={"building_elf_siege", "building_elf_siege_decal", "building_elf_siege_frame", }, selectionscaling=8},
[205] = {mesh={"building_dwarf_siege", "building_dwarf_siege_decal", "building_dwarf_siege_frame", }, selectionscaling=12},
[206] = {mesh={"building_orc_siege", "building_orc_siege_decal", "building_orc_siege_frame", }, selectionscaling=8},
[207] = {mesh={"building_troll_siege", "building_troll_siege_decal", "building_troll_siege_frame", }, selectionscaling=8},
[208] = {mesh={"building_darkelf_siege", "building_darkelf_siege_decal", "building_darkelf_siege_frame", }, selectionscaling=8},
[209] = {mesh={"building_darkelf_tower_blackmagic", "building_darkelf_tower_blackmagic_decal", }, selectionscaling=5},
[210] = {mesh={"building_skeleton_tower_skull", "building_skeleton_tower_skull_decal", }, selectionscaling=5},
[211] = {mesh={"building_skeleton_tower_skull", "building_skeleton_tower_skull_decal", }, selectionscaling=5},
[212] = {mesh={"building_orc_tower_firemagic", "building_orc_tower_firemagic_decal", }, selectionscaling=6},
[213] = {mesh={"building_blade_tower", }, selectionscaling=11},
}
